
import { Verb } from './types';

export const IRREGULAR_VERBS: Verb[] = [
  { base: 'be', pastSimple: 'was/were', pastParticiple: 'been', definition: 'Exist or live.' },
  { base: 'begin', pastSimple: 'began', pastParticiple: 'begun', definition: 'Start to do something.' },
  { base: 'break', pastSimple: 'broke', pastParticiple: 'broken', definition: 'Separate into pieces as a result of a blow, shock, or strain.' },
  { base: 'bring', pastSimple: 'brought', pastParticiple: 'brought', definition: 'Take or go with (someone or something) to a place.' },
  { base: 'buy', pastSimple: 'bought', pastParticiple: 'bought', definition: 'Obtain in exchange for payment.' },
  { base: 'build', pastSimple: 'built', pastParticiple: 'built', definition: 'Construct by putting parts or materials together.' },
  { base: 'choose', pastSimple: 'chose', pastParticiple: 'chosen', definition: 'Decide on a course of action.' },
  { base: 'come', pastSimple: 'came', pastParticiple: 'come', definition: 'Move or travel toward or into a place thought of as near.' },
  { base: 'cost', pastSimple: 'cost', pastParticiple: 'cost', definition: 'Require the payment of a specified sum of money.' },
  { base: 'do', pastSimple: 'did', pastParticiple: 'done', definition: 'Perform an action, the precise nature of which is often unspecified.' },
  { base: 'draw', pastSimple: 'drew', pastParticiple: 'drawn', definition: 'Produce a picture or diagram by making lines and marks.' },
  { base: 'drink', pastSimple: 'drank', pastParticiple: 'drunk', definition: 'Take (a liquid) into the mouth and swallow.' },
  { base: 'drive', pastSimple: 'drove', pastParticiple: 'driven', definition: 'Operate and control the direction and speed of a motor vehicle.' },
  { base: 'eat', pastSimple: 'ate', pastParticiple: 'eaten', definition: 'Put (food) into the mouth and chew and swallow it.' },
  { base: 'fall', pastSimple: 'fell', pastParticiple: 'fallen', definition: 'Move downward, typically rapidly and freely without control.' },
  { base: 'feel', pastSimple: 'felt', pastParticiple: 'felt', definition: 'Experience an emotion or sensation.' },
  { base: 'find', pastSimple: 'found', pastParticiple: 'found', definition: 'Discover or perceive by chance or unexpectedly.' },
  { base: 'fly', pastSimple: 'flew', pastParticiple: 'flown', definition: 'Move through the air using wings.' },
  { base: 'forget', pastSimple: 'forgot', pastParticiple: 'forgotten', definition: 'Fail to remember.' },
  { base: 'get', pastSimple: 'got', pastParticiple: 'gotten', definition: 'Come to have or hold (something); receive.' },
  { base: 'give', pastSimple: 'gave', pastParticiple: 'given', definition: 'Freely transfer the possession of something to someone.' },
  { base: 'go', pastSimple: 'went', pastParticiple: 'gone', definition: 'Move from one place to another; travel.' },
  { base: 'grow', pastSimple: 'grew', pastParticiple: 'grown', definition: 'Undergo natural development by increasing in size.' },
  { base: 'have', pastSimple: 'had', pastParticiple: 'had', definition: 'Possess, own, or hold.' },
  { base: 'hear', pastSimple: 'heard', pastParticiple: 'heard', definition: 'Perceive with the ear the sound made by (someone or something).' },
  { base: 'know', pastSimple: 'knew', pastParticiple: 'known', definition: 'Have knowledge or information about something.' },
  { base: 'leave', pastSimple: 'left', pastParticiple: 'left', definition: 'Go away from.' },
  { base: 'make', pastSimple: 'made', pastParticiple: 'made', definition: 'Form (something) by putting parts together.' },
  { base: 'meet', pastSimple: 'met', pastParticiple: 'met', definition: 'Arrange to be in the same place as someone.' },
  { base: 'pay', pastSimple: 'paid', pastParticiple: 'paid', definition: 'Give (someone) money that is due for work done.' },
  { base: 'put', pastSimple: 'put', pastParticiple: 'put', definition: 'Move to or place in a particular position.' },
  { base: 'read', pastSimple: 'read', pastParticiple: 'read', definition: 'Look at and comprehend the meaning of written or printed matter.' },
  { base: 'run', pastSimple: 'ran', pastParticiple: 'run', definition: 'Move at a speed faster than a walk.' },
  { base: 'say', pastSimple: 'said', pastParticiple: 'said', definition: 'Utter words so as to convey information, an opinion, a feeling, etc.' },
  { base: 'see', pastSimple: 'saw', pastParticiple: 'seen', definition: 'Perceive with the eyes; discern visually.' },
  { base: 'sell', pastSimple: 'sold', pastParticiple: 'sold', definition: 'Give or hand over (something) in exchange for money.' },
  { base: 'send', pastSimple: 'sent', pastParticiple: 'sent', definition: 'Cause to go or be taken to a particular destination.' },
  { base: 'sing', pastSimple: 'sang', pastParticiple: 'sung', definition: 'Make musical sounds with the voice.' },
  { base: 'sit', pastSimple: 'sat', pastParticiple: 'sat', definition: 'Adopt or be in a position in which one\'s weight is supported by one\'s buttocks.' },
  { base: 'sleep', pastSimple: 'slept', pastParticiple: 'slept', definition: 'Be in a state of rest.' },
  { base: 'speak', pastSimple: 'spoke', pastParticiple: 'spoken', definition: 'Say something in order to convey information or an opinion.' },
  { base: 'spend', pastSimple: 'spent', pastParticiple: 'spent', definition: 'Pay out (money) in buying or hiring goods or services.' },
  { base: 'stand', pastSimple: 'stood', pastParticiple: 'stood', definition: 'Have or maintain an upright position, supported by one\'s feet.' },
  { base: 'swim', pastSimple: 'swam', pastParticiple: 'swum', definition: 'Propel the body through water by using the limbs.' },
  { base: 'take', pastSimple: 'took', pastParticiple: 'taken', definition: 'Lay hold of (something) with one\'s hands; reach for and hold.' },
  { base: 'teach', pastSimple: 'taught', pastParticiple: 'taught', definition: 'Show or explain to (someone) how to do something.' },
  { base: 'tell', pastSimple: 'told', pastParticiple: 'told', definition: 'Communicate information to someone in spoken or written words.' },
  { base: 'think', pastSimple: 'thought', pastParticiple: 'thought', definition: 'Have a particular belief or idea.' },
  { base: 'understand', pastSimple: 'understood', pastParticiple: 'understood', definition: 'Perceive the intended meaning of (words, a language, or a speaker).' },
  { base: 'wear', pastSimple: 'wore', pastParticiple: 'worn', definition: 'Have on one\'s body or a part of one\'s body as clothing, decoration, etc.' },
  { base: 'win', pastSimple: 'won', pastParticiple: 'won', definition: 'Be successful or victorious in a contest or conflict.' },
  { base: 'write', pastSimple: 'wrote', pastParticiple: 'written', definition: 'Mark (letters, words, or other symbols) on a surface.' },
];
